app = 'package-tracking-server'
primary_region = 'ord'

[build]
  [build.args]
    GO_VERSION = '1.23'


[env]
  PORT = '8080'
  DATABASE_PATH="/data/data.db"

[mounts]
  source = "myapp_data"
  destination = "/data"
  initial_size = "1gb"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
