basePath: /api
definitions:
  api.loginInfo:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  api.loginResponse:
    properties:
      error:
        type: string
      token:
        type: string
    type: object
  api.registerResponse:
    properties:
      error:
        type: string
      token:
        type: string
    type: object
  api.registrationInfo:
    properties:
      company:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  api.startTracking:
    properties:
      token:
        type: string
      tracking_number_groups:
        items:
          $ref: '#/definitions/api.trackingNumberGroup'
        type: array
    type: object
  api.startTrackingResp:
    properties:
      error:
        type: string
    type: object
  api.trackingNumberGroup:
    properties:
      group_name:
        type: string
      tracking_numbers:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
  title: Tracking Server API
paths:
  /login:
    post:
      consumes:
      - application/json
      operationId: login-user
      parameters:
      - description: Login Info
        in: body
        name: loginInfo
        required: true
        schema:
          $ref: '#/definitions/api.loginInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.loginResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.loginResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.loginResponse'
      summary: Verifies and logs in the user, returning a token
  /register:
    post:
      consumes:
      - application/json
      operationId: register-user
      parameters:
      - description: Registration Info
        in: body
        name: registrationInfo
        required: true
        schema:
          $ref: '#/definitions/api.registrationInfo'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.registerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.registerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.registerResponse'
      summary: Registers a new user
  /start_tracking:
    post:
      consumes:
      - application/json
      operationId: start-tracking-groups
      parameters:
      - description: Tracking Info
        in: body
        name: registrationInfo
        required: true
        schema:
          $ref: '#/definitions/api.startTracking'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.startTrackingResp'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/api.startTrackingResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.startTrackingResp'
      summary: Starts tracking the package tracking numbers given by the user
swagger: "2.0"
