basePath: /api
definitions:
  api.loginInfo:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  api.loginResponse:
    properties:
      error:
        type: string
      token:
        type: string
    type: object
  api.registerResponse:
    properties:
      error:
        type: string
      token:
        type: string
    type: object
  api.registrationInfo:
    properties:
      company:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  title: Tracking Server API
paths:
  /login:
    post:
      consumes:
      - application/json
      operationId: login-user
      parameters:
      - description: Login Info
        in: body
        name: loginInfo
        required: true
        schema:
          $ref: '#/definitions/api.loginInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.loginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.loginResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.loginResponse'
      summary: Verifies and logs in the user, returning a token
  /register:
    post:
      consumes:
      - application/json
      operationId: register-user
      parameters:
      - description: Registration Info
        in: body
        name: registrationInfo
        required: true
        schema:
          $ref: '#/definitions/api.registrationInfo'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.registerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.registerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.registerResponse'
      summary: Registers a new user
swagger: "2.0"
